#!/usr/bin/perl

# lintian-inplace: Run lintian from the source tree.
#
# Symlink it wherever you like, but don't copy it, or it won't be able
# to find the source tree.

use strict;

use Cwd qw(realpath);
use File::Basename qw(dirname);

my $LINTIAN_ROOT = dirname(realpath(__FILE__));
$ENV{LINTIAN_ROOT} = $LINTIAN_ROOT;

my $lintian = "$LINTIAN_ROOT/frontend/lintian";
exec $lintian, @ARGV;
die "could not invoke $lintian";
